Initialize multiple language and start translations
mrvautin/expressCart pull request #91
Opened 2019-10-29 19:51 UTC by anddimario

### Issue
https://github.com/mrvautin/expressCart/issues/87

### Todo
- complete view translations
- review

2019-10-29 22:10 UTC, mrvautin commented
Looks ok so far. There is a heap of linting. Are you using the eslint file in the project?

2019-10-30 12:53 UTC, anddimario commented
yes, i'm using, i'll fix linting errors later

2019-11-02 19:30 UTC, anddimario commented
I think that i've complete the translation (en and it), about linting, it seems that are the same master repository results (i've not edit lots of js files).
If you agree, i'll set the pr for the review.

2019-11-02 23:20 UTC, mrvautin commented
Look good mate. Seems there is still some whitespace linting happening in the `getStatusColor` function of the `app.js` file. 

Maybe switch to review and I can highlight anything I see.

2019-11-03 13:41 UTC, anddimario commented
It seems that there're some conflict, i'll wait your input to know how you would proceed :)

2019-11-04 04:29 UTC, mrvautin commented
Could you try rebasing back onto master? Most should not be conflicts.

2019-11-04 12:56 UTC, anddimario commented
I've merged upstream into my fork and solved conflict, could it be good for you?

2019-11-05 03:48 UTC, mrvautin requested changes
Looks good mate. Just a few comments. I appreciate your contributions.

Seems like your eslint isn't working as expected as there are a lot of whitespace changes which don't show on `master`.

2019-11-05 03:48 UTC, mrvautin commented on app.js
> +    res.locals.languages = i18n.getLocales();
Can this be moved to line 271 with the `req.handlebars = handlebars;` line?

2019-11-05 03:48 UTC, mrvautin commented on config/settings.json
> -    "footerHtml": "&lt;h4 class=&quot;text-center&quot;&gt;Powered by expressCart&lt;/h4&gt;",
Can you revert all changes in the `settings.json file` except the new additions?

2019-11-05 03:48 UTC, mrvautin commented on package.json
> +    "moment-recur": "^1.0.7",
This appears unused. Can it be removed?

2019-11-05 03:48 UTC, mrvautin commented on views/customers.hbs
> -        <p class="text-warning top-pad-10">Customers can be filtered by: email, name or phone numnber</p>
`numnber` typo. Can you change to `number`. Also need to update translation file.

2019-11-05 03:48 UTC, mrvautin commented on views/themes/Cloth/payment_complete.hbs
> -                <h2 class="text-danger">Your payment has failed. Please try again or contact us.</h2>
Looks like a duplicate. Should have the failed message.

2019-11-05 03:48 UTC, mrvautin commented on views/themes/Material/payment_complete.hbs
> +                <h2 class="text-danger">{{ @root.__ "Your payment has been successfully processed" }}</h2>
This should have the failed message.

2019-11-05 03:48 UTC, mrvautin commented on views/themes/Mono/payment_complete.hbs
> +                <h2 class="text-danger">{{ @root.__ "Your payment has been successfully processed" }}</h2>
This should have the failed message.

2019-11-05 03:48 UTC, mrvautin commented on app.js
> -            case'Paid':
Lots of whitespace changes. Is your eslint setup correctly?

2019-11-05 11:29 UTC, anddimario commented
i think that i've solved errors

2019-11-05 20:48 UTC, mrvautin commented
Thanks. I cannot merge as there are more conflicts. Can you do one last rebase onto master and I will merge.

2019-11-06 08:01 UTC, anddimario commented
it seems that i can fetch nothing from upstream, and here github doesn't show conflicts, are you sure that you don't refer to a specific branch?

2019-11-06 08:30 UTC, mrvautin approved these changes

2019-11-06 08:31 UTC, merged

2019-11-06 08:43 UTC, mrvautin commented
It seems Github has changed. I've merged your changes now. Thanks.